### ISSUE TITLE
analytics for quote image share click

### ISSUE THREAD

**Issue by eads** [nprapps/commencement#187]

**Comment by dannydb** [comment]
This actually was implemented already, though it’s it the template as an onclick attribute:

```
<li class="prompt">Share this <a href="{{ image }}" target="_blank" onclick="_gaq.push(['_trackEvent', 'Social', 'Click Image Link From Speech Detail', '{{ PROJECT_SLUG }}']);">quote image</a></li>
```

**Comment by eads** [comment]
That goes to the old analytics tracker. We also need something that uses
ANALYTICS.trackEvent to send it to the Viz team account.
